# Generated by Django 4.0 on 2022-01-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exemple_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/examples'),
        ),
    ]
