# Generated by Django 4.0 on 2022-03-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_gallery_status_photo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('hide', 'hide'), ('published', 'published')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('new', 'new'), ('hide', 'hide'), ('published', 'published')], default='new'),
        ),
    ]
