# Generated by Django 4.0 on 2022-03-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_alter_gallery_status_alter_photo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('hide', 'hide'), ('published', 'published')], default='new', max_length=10),
        ),
    ]
