# Generated by Django 4.0 on 2022-04-07 11:11

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_alter_photo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='galleries/images/%Y/%m/%d/'),
        ),
    ]
