# Generated by Django 4.0 on 2021-12-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Books',
        ),
    ]
