# Generated by Django 4.0 on 2022-01-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('books', '0002_rename_post_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='tags',
            field=models.ManyToManyField(related_name='books', to='tags.Tag'),
        ),
    ]
