# Generated by Django 4.0 on 2022-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers/%Y/%m/%d/'),
        ),
    ]
