# Generated by Django 4.0 on 2022-03-01 12:32

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='books/covers/%Y/%m/%d/'),
        ),
    ]
