# Generated by Django 4.0 on 2022-04-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_books_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autorzy'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
        migrations.AlterModelOptions(
            name='borrow',
            options={'verbose_name': 'Wypożyczenie', 'verbose_name_plural': 'Wypożyczenia'},
        ),
    ]
